export const SECRET = {
  AFDIAN_TOKEN: 'AFDIAN_TOKEN',
  PATREON_SECRET: 'PATREON_SECRET',
  SERVER_APIKEY: 'SERVER_APIKEY',
  SERVER_APIKEY_TEST: 'SERVER_APIKEY_TEST',
  TEST_SECRET: 'TEST_SECRET',
  GA4_MEASUREMENT_ID: 'GA4_MEASUREMENT_ID',
  GA4_API_SECRET: 'GA4_API_SECRET',
};

export const GetSecretValue = (key: string): string => {
  return process.env[key];
};
